import useTextDirection from '../hooks/useTextDirection';
import './global.css';

export const metadata = {
  title: 'Welcome to apps/myapp-two',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const dir = useTextDirection(locale);
  return (
    <html lang={locale} dir={dir}>
      <body>{children}</body>
    </html>
  );
}
