import { dir } from 'i18next';
import { languages } from '../i18n/settings';

import './global.css';

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export const metadata = {
  title: 'Welcome to myapp-one',
  description: 'Generated by create-nx-workspace',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}

export default function RootLayout({
  children,
  params: { lang },
}: RootLayoutProps) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body>{children}</body>
    </html>
  );
}
